import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import { Geist, Geist_Mono } from "next/font/google";
import { PageTransition } from "@/components/layout/PageTransition";
import { AuthControls } from "@/components/auth/AuthControls";
import { getAuthSession } from "@/lib/auth-session";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getAuthSession();
  const authUserId = session?.user.id;

  let role: "BRAND" | "CREATOR" | null = null;
  let credits = 0;
  let earnings = 0;

  if (authUserId) {
    const user = await prisma.user.findUnique({
      where: {
        authUserId,
      },
      select: {
        role: true,
        credits: true,
        earnings: true,
      },
    });

    if (user) {
      role = user.role;
      credits = user.credits;
      earnings = user.earnings;
    }
  }

  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-zinc-800 bg-zinc-950/90 backdrop-blur-sm">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4">
            <span className="text-base font-semibold tracking-tight text-zinc-100">
              CloutMint
            </span>
            <div className="flex items-center gap-5">
              {role === "BRAND" && (
                <span className="text-sm font-medium text-zinc-300">
                  Credits:{" "}
                  <span className="text-zinc-100">{credits}</span>
                </span>
              )}
              {role === "CREATOR" && (
                <span className="text-sm font-medium text-zinc-300">
                  Earnings:{" "}
                  <span className="text-zinc-100">${earnings}</span>
                </span>
              )}
              <AuthControls />
            </div>
          </div>
        </header>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
